// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZIbs_5x_cFQ9s5ZEDuLa_a8OT9k3_l4',
    appId: '1:714995937854:web:8c0ec214b3c4b996d3176f',
    messagingSenderId: '714995937854',
    projectId: 'notedpak-app',
    authDomain: 'notedpak-app.firebaseapp.com',
    storageBucket: 'notedpak-app.firebasestorage.app',
    measurementId: 'G-XCV9L0NP3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY3R8SafCTmNQZW2I380gM13szOcoUY5Q',
    appId: '1:714995937854:android:5e3501bb2cd6f56cd3176f',
    messagingSenderId: '714995937854',
    projectId: 'notedpak-app',
    storageBucket: 'notedpak-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFrs34RKtIbAn1b3VsIxHAjAYJHO0vr2g',
    appId: '1:714995937854:ios:7609572c10a73ca7d3176f',
    messagingSenderId: '714995937854',
    projectId: 'notedpak-app',
    storageBucket: 'notedpak-app.firebasestorage.app',
    iosBundleId: 'com.example.notedPak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFrs34RKtIbAn1b3VsIxHAjAYJHO0vr2g',
    appId: '1:714995937854:ios:7609572c10a73ca7d3176f',
    messagingSenderId: '714995937854',
    projectId: 'notedpak-app',
    storageBucket: 'notedpak-app.firebasestorage.app',
    iosBundleId: 'com.example.notedPak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpZIbs_5x_cFQ9s5ZEDuLa_a8OT9k3_l4',
    appId: '1:714995937854:web:0870e208d93dcccbd3176f',
    messagingSenderId: '714995937854',
    projectId: 'notedpak-app',
    authDomain: 'notedpak-app.firebaseapp.com',
    storageBucket: 'notedpak-app.firebasestorage.app',
    measurementId: 'G-NQ6PGKP6HG',
  );
}
